In [22]:
import numpy as np

In [23]:
np.exp(2)

7.38905609893065

In [24]:
np.log10(2)

0.3010299956639812

In [25]:
np.log(2)

0.6931471805599453

In [26]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])


In [27]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(1/arr1)
print(arr1 ** arr2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1.         0.5        0.33333333 0.25       0.2       ]
[      1     128    6561  262144 9765625]


In [28]:
arr = np.array([1, 2,3, 4, 5,6 ,7, 4, 3, 4])

np.eye(arr)

print(arr)

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
mt9 = np.arange(1, 10).reshape(3, 3)
mt10 = np.arange(1, 10).reshape(3, 3)

In [ ]:
mt9 @ mt10

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
mt11 = np.arange(1, 17).reshape(4, 4)
mt12 = np.arange(1, 17).reshape(4, 4)


In [ ]:
#mt11 @ mt12 OR 
# np.dot(mt11, mt12)
np.linalg.multi_dot([mt11, mt12])

array([[ 90, 100, 110, 120],
       [202, 228, 254, 280],
       [314, 356, 398, 440],
       [426, 484, 542, 600]])

In [ ]:
'''Solve these equations:
x+2y+3z=10
2x+3y+z=15
x+y+2z=20'''

a = np.array([[1, 2, 3], [2, 3, 1], [1, 1, 2]])
b = np.array([10, 15, 20])
x, y, z = np.linalg.solve(a, b)
print(x)
print(y)
print(z)

26.25
-13.75
3.75


In [31]:
# Transpose of a matrix
mt7 = np.arange(1, 10).reshape(3, 3)
# mt7.T
mt = np.transpose(mt7)


In [ ]:
fm = mt7 @ mt
print(fm.max())
# OR np.max(fm)
print(fm.min())
print(fm.sum())

194
14
693


In [ ]:
# [0, 1)
rand_mat = np.random.rand(5)
rand_mat

array([0.97952614, 0.87804679, 0.93485244, 0.85487957, 0.98828507])

In [ ]:
ran_mat = np.random.rand(3, 3)
ran_mat
# randn

array([[0.94103562, 0.94729782, 0.9242282 ],
       [0.92184282, 0.03279459, 0.60694997],
       [0.72111301, 0.90153354, 0.10186413]])

In [ ]:
# NORMAL: curve having mean, median same and SD = 1
# Standardization & Normalization
# poisson, normal, bernoiullue
# std vs nml dist


In [39]:
rnd_mt = np.random.randint(2, 6, 10)
rnd_mt

array([3, 2, 4, 5, 5, 2, 2, 3, 5, 4])

In [44]:
rnd_mtt = np.random.randint(1, 10, [3, 5])

print(rnd_mtt, '\n')

rnd_mtt

[[8 7 3 7 4]
 [5 8 9 9 8]
 [7 5 9 9 4]] 



array([[8, 7, 3, 7, 4],
       [5, 8, 9, 9, 8],
       [7, 5, 9, 9, 4]])